### ISSUE TITLE
[fxos] Bring bzdeck's performance in parity with Bugzilla lite

### ISSUE THREAD

**Issue by nt1m** [bzdeck/bzdeck#306] opened 2015-09-13 21:14 UTC
Bugzilla lite runs much faster than bzdeck on Firefox OS. It also looks better.

**Comment by kyoshino** [comment] 2015-09-13 21:40
Performance and mobile optimization is planned for [Beta 14](https://github.com/bzdeck/bzdeck/milestones/Beta%2014). But it may be delayed because my Flame phone used for testing was stolen yesterday  :crying_cat_face:


We could do better anyway, though it's difficult to compare BzDeck with Bugzilla Lite. Bugzilla Lite has been built exclusively for Firefox OS, while BzDeck is a cross platform app.

**Comment by kyoshino** [comment] 2015-11-05 22:54
Marking this issue duplicate of #290.

**Closed by kyoshino** 2015-11-05 22:54 UTC
Labels: mobile, performance
